### ISSUE TITLE
Lighthouse PWA score below 100

### ISSUE THREAD

**Issue by markgoho** [mdn/pwa-examples#3]
This is the MDN example of a PWA. Surely the score should be continuously monitored and updated to show 100 in a Lighthouse Audit.
![image](https://user-images.githubusercontent.com/9759954/39079765-1b06eb7a-44ef-11e8-90a8-f223c2adc5cf.png)

**Comment by chrisdavidmills** [comment]
This is a good call! I have already fixed two of the issues brought up in Lighthouse, but I think we need to also mess around with the layout a bit, make it more responsive, to fix the third point. @end3r , flagging you here so you know about this.

**Comment by end3r** [comment]
Yes, I still have that on my TODO list, thanks for the reminder - I'll update it soon.

**Comment by end3r** [comment]
![score](https://user-images.githubusercontent.com/373344/40352410-098f9c88-5daf-11e8-8a5a-4fab6686c7b5.png)
I think this one can be closed now, @chrisdavidmills.

**Comment by chrisdavidmills** [comment]
OK.
